### ISSUE TITLE
Script for double or nothing not working 6.11.2022

### ISSUE THREAD

**Issue by OlavHandeland** [argorar/Imperia-Scripts#1]
It might be a problem with my translation of the original language, maybe I misunderstood the instructions.

If not, this script does not work any longer.

I did the following steps:

1. Open the Tavern menu in the Imperia Online web page via Google Chrome 106.0.5249.119
2. Enter the script through the console and see the result
3. When lost a bet, clicking on the X button on the top window with the cards
4. Enter the script again through the console with the Tavern menu open
5. The number does not change from zero

![image](https://user-images.githubusercontent.com/5259597/200186165-61362d68-50f5-4234-8887-d80c4f07dba4.png)

**Comment by argorar** [comment]
This does not longer work. It has already few years and is already patched.
